### ISSUE TITLE
Gaping hole between title and preview on mobile

### ISSUE THREAD

**Issue by mcmillan** [Lostmyname/monkey#16]
This is a weird one - appears to be intermittent. Possibly related to some kind of caching? iPhone 6, iOS 8.1. 
![image](https://cloud.githubusercontent.com/assets/1315466/5569242/c34f9208-8f64-11e4-89ee-67335036473f.jpg)

**Comment by callumacrae** [comment]
I have no idea what causes this one. I think it's something to do with the images being displayed at their original size and then shrunk using JS, but that doesn't make sense because it's supposed to happen the other way round.

**Comment by callumacrae** [comment]
Yesterday this was happening every single time I loaded up monkey on my phone. It wasn't fun, and this needs looking into.

**Comment by callumacrae** [comment]
has seemingly gone away
