### ISSUE TITLE
Bug with final page

### ISSUE THREAD

**Issue by metade** [Lostmyname/monkey#18]
![error_in_last_page2](https://cloud.githubusercontent.com/assets/3056/6186140/c9b8f648-b36d-11e4-981b-34db0a8b865f.jpg)

Description: Customer is unable to view final page of preview, despite trying multiple browsers and devices. Everything appeared fine when I tried to view preview on my computer (Using Firefox). Screenshot attached.
Submitted by: lydia@lostmy.name
Broswer: Chrome, Firefox, IE
Order ID: 
Reamaze Ticket: https://lostmyname.reamaze.com/admin/conversations/question-not-covered-8567
Customer email: 
Names of book: Olivia
Print house: Not Applicable
Customer issue resolved? : No - they are unable to purchase / do what they want

**Comment by callumacrae** [comment]
pls can i see the screenshot

**Comment by callumacrae** [comment]
That's most likely not an issue with monkey: monkey is sent the file paths by the server, and it looks like one of them was invalid (or blocked by the network?)

This is basically impossible to do anything with without replicating here.
