### ISSUE TITLE
hyphen usage within a child's name reduces the printed page chars to 11 from 12 (counts the hyphen)

### ISSUE THREAD

**Issue by DaveLaceyLMN** [Lostmyname/monkey#37]
Configuration:
All

Expected result.
Given that the hyphen is not in the book as a page, then we should allow 12 chars excluding the hyphen.  So 13.

Actual result:
We count the hyphen, so the user is -1 char they can utilise on the child's name

Note:  beware the same may be true for space usage vs hyphen
Note: JS on/Off = same

Steps to reproduce:
1.) go to live url 
2.) attempt to enter 12 chars + a hyphen as a child's name, validation fails it --> failure point

**Comment by callumacrae** [comment]
Moved to eagle

**Comment by DaveLaceyLMN** [comment]
need to be sure that the book itself can handle that in the last page
